# Generated by Django 3.2.15 on 2022-09-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one_off_fee_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='one_off_fee',
            name='area',
            field=models.CharField(default='Area01', max_length=10),
        ),
        migrations.AddField(
            model_name='one_off_fee',
            name='city',
            field=models.CharField(default='Ho Chi Minh city', max_length=20),
        ),
        migrations.AlterField(
            model_name='one_off_fee',
            name='bookdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='one_off_fee',
            name='feelist',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='one_off_fee',
            name='starttime',
            field=models.TimeField(),
        ),
    ]
